Rails.application.routes.draw do
  root "game#index"
  post "explore", to: "game#explore"
  post "attack", to: "game#attack"
  post "sword_skill", to: "game#sword_skill"
  post "use_battle_item", to: "game#use_battle_item"
  post "use_item", to: "game#use_item"
  post "escape", to: "game#escape"
  post "start_rest", to: "game#start_rest"
  post "use_rest_skill", to: "game#use_rest_skill"
  post "use_rest_item", to: "game#use_rest_item"
  post "end_rest", to: "game#end_rest"
  post "move", to: "game#move"
  post "stroll", to: "game#stroll"
  post "item_shop", to: "game#item_shop"
  post "blacksmith", to: "game#blacksmith"
  post "buy_bronze_sword", to: "game#buy_bronze_sword"
  post "equip_weapon", to: "game#equip_weapon"
  post "equip_armor", to: "game#equip_armor"
  post "inn", to: "game#inn"
  post "allocate_strength", to: "game#allocate_strength"
  post "allocate_agility", to: "game#allocate_agility"
end
